# Dockerfile for local development

FROM node:23.11.1-alpine3.21

# create directory on container
WORKDIR /frontend/app 

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /frontend/app

RUN npm install

COPY . /frontend/app

CMD ["npm", "start"]