# Dockerfile for local development

FROM node:16.8.0-alpine3.13

# create directory on container
WORKDIR /frontend/app 

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /frontend/app

RUN npm install

COPY . /frontend/app

CMD ["npm", "start"]